### ISSUE TITLE
Rata does not support OPTIONS

### ISSUE THREAD

**Issue by aaronshurley** [tedsuo/rata#2]
When deploying a go app to PWS as a server using rata we hit a bug where our front end javascript app deployed elsewhere was unable to talk to it because rata does not support the `OPTIONS` http method. 
- Aaron and Morgan

**Comment by tedsuo** [comment]
Hmmm, github notifications are not what they used to be. Do you still need this? I will probably add it anyways.

**Comment by mfine30** [comment]
Yes, this is a use case we have

**Comment by tedsuo** [comment]
Closing this with commit f37f1815b8642351268bdfaf59033c448311c3df

Rata now supports all valid methods, and has constants for each method name as a convenience.
