### ISSUE TITLE
How to loop the handlers 

### ISSUE THREAD

**Issue by tianxiaoliang** [tedsuo/rata#3]
petHandlers := rata.Handlers{
    "get_pet":    newGetPetHandler(),
    "create_pet": newCreatePetHandler(),
    "update_pet": newUpdatePetHandler(),
    "delete_pet": newDeletePetHandler()
  }
router, err = rata.NewRouter(rteRoutes, petHandlers)

after I defined those handlers, call it in main func
http.Handle("/", router)

How can I get each of handler, I want to add API level rate limit.So I want to get them from the router

**Comment by tedsuo** [comment]
Sorry I am in Cuba with very limited internet until the 21st. But the
router is itself a handler, you can wrap that if you want to rate limit
them all. Or you can wrap the individual handlers when you create them, or
iterate over the map of handlers to create a new map. Hope that helps!

-ted

**Comment by tedsuo** [comment]
Hi @tianxiaoliang, I'm closing this issue as it's stale, but please reopen it if you have any further questions.
