### ISSUE TITLE
Handle trailing slash in host URL

### ISSUE THREAD

**Issue by mariash** [tedsuo/rata#4]
If provided host has a trailing slash rata will generate request with double slashes between host URL and path. That results in that some servers fail to handle such paths and return 404.

This is happening for example in case if CLI user enters API URL as `https://api.host.com/` the subsequent requests to CloudController will return 404 since request URL will look like `https://api.host.com//v2/info`. We currently strip trailing slash from host URL, but it would be nice if rata could handle this case.

**Comment by tedsuo** [comment]
I agree that no one would ever want that, so this is a reasonable convenience. PR looks good, thanks!
